### ISSUE TITLE
PHPUnit listener doesn't plays well with Bugsnag

### ISSUE THREAD

**Issue by driesvints** [nunomaduro/collision#27]
I'm not really sure if I should report this to the Bugsnag Laravel repository or this one. I get the following stack trace when I trigger a failing PHPUnit test with the Collision listener enabled. When I disable the listener I get the normal stack trace.

*Might* be related to this issue but unsure: https://github.com/bugsnag/bugsnag-laravel/issues/263

Laravel 5.5.3
PHP 7.1.1
Collision 1.1.9
Bugsnag-Laravel 2.9.0

```
> phpunit --stop-on-failure 'tests/Functional/Accounts/AccountsTest.php'
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.


  Laravel\BrowserKitTesting\HttpException : A request to [http://localhost/account/selec] failed. Received status code [404].

  at [internal]: 0
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Container/Container.php:918
Stack trace:
#0 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /var/www/development.promoter/current/ven in /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 918
PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\BugsnagLaravel\Facades\Bugsnag::notifyException() in /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
Stack trace:
#0 /var/www/development.promoter/current/app/Exceptions/Handler.php(54): Illuminate\Support\Facades\Facade::__callStatic('notifyException', Array)
#1 /var/www/development.promoter/current/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(70): BeatSwitch\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->han in /var/www/development.promoter/current/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 221
```

**Comment by nunomaduro** [comment]
@driesvints I will check that this weekend 👍

**Comment by nunomaduro** [comment]
@driesvints Please check if you have the following line on bootstrap/app.php:

```
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);
```

On your testing, are you using methods like `withExceptionHandling` or `withoutExceptionHandling` ?

**Comment by nunomaduro** [comment]
@driesvints Please perform: `composer update nunomaduro/collision` and tell me the results.

**Comment by driesvints** [comment]
@nunomaduro that did it! Thanks :)

**Comment by driesvints** [comment]
@nunomaduro there's one thing I noticed. When using the listener, Collision stops PHPUnit at the first failure instead of running the remainder of tests. Is that intentional?

**Comment by nunomaduro** [comment]
@driesvints Is intencional. Just like Whoops on web-development, it stops when you have mistake/or a failure.

**Comment by driesvints** [comment]
@nunomaduro ok, we probably won't install the listener for PHPUnit then. When running tests, especially on a CI env, we'd still like all of the tests to run and gather enough info about which tests are failing.

**Comment by nunomaduro** [comment]
Hummm! Thanks @driesvints for the feedback. I will take that in consideration for later. You may want to still use Collision for your artisan commands 🙂

**Comment by driesvints** [comment]
Yep, definitely going to do that! :)
