### ISSUE TITLE
Failed to open stream: Too many open files

### ISSUE THREAD

**Issue by fisher926** [nunomaduro/collision#299]
Hello!
Get this error.
Changed ulimit -n and fs.file-max, it didn't work.
```
[2024-01-23 15:48:13] production.ERROR: Uncaught ErrorException: include(/var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php): Failed to open stream: Too many open files in /var/www/laravel/vendor/composer/ClassLoader.php:576
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/laravel/vendor/composer/ClassLoader.php(576): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/laravel/vendor/composer/ClassLoader.php(576): include('...')
#3 /var/www/laravel/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#4 /var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php(54): Composer\Autoload\ClassLoader->loadClass()
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): NunoMaduro\Collision\Adapters\Laravel\CollisionServiceProvider->NunoMaduro\Collision\Adapters\Laravel\{closure}()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build()
#7 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(857): Illuminate\Container\Container->resolve()
#8 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve()
#9 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(842): Illuminate\Container\Container->make()
#10 /var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(66): Illuminate\Foundation\Application->make()
#11 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(211): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
#12 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(197): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#15 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: include(/var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php): Failed to open stream: Too many open files in /var/www/laravel/vendor/composer/ClassLoader.php:576
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/laravel/vendor/composer/ClassLoader.php(576): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/laravel/vendor/composer/ClassLoader.php(576): include('...')
#3 /var/www/laravel/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#4 /var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php(54): Composer\\Autoload\\ClassLoader->loadClass()
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): NunoMaduro\\Collision\\Adapters\\Laravel\\CollisionServiceProvider->NunoMaduro\\Collision\\Adapters\\Laravel\\{closure}()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build()
#7 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(857): Illuminate\\Container\\Container->resolve()
#8 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve()
#9 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(842): Illuminate\\Container\\Container->make()
#10 /var/www/laravel/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(66): Illuminate\\Foundation\\Application->make()
#11 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(211): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->renderForConsole()
#12 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(197): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderForConsole()
#13 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#14 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#15 {main}
  thrown at /var/www/laravel/vendor/composer/ClassLoader.php:576)
[stacktrace]
#0 {main}
"} 
```

**Comment by finalblast** [comment]
@nunomaduro same issue

**Comment by iwebmaestro** [comment]
@nunomaduro same issue, please close issue

**Comment by baar1809** [comment]
Oh, this problem has been bothering me for a long time

**Comment by Arey125** [comment]
same issue

**Comment by heavenlybilly** [comment]
Hi, could you look into resolving this issue as soon as possible?
