### ISSUE TITLE
Fatal error when phpunit test case has no methods

### ISSUE THREAD

**Issue by sw-double** [nunomaduro/collision#31]
This is the error
```
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

Fatal error: Uncaught Error: Call to a member function stopOnFailure() on null in /vendor/nunomaduro/collision/src/Adapters/Phpunit/Listener.php:141
Stack trace:
#0 /vendor/phpunit/phpunit/src/Framework/TestResult.php(395): NunoMaduro\Collision\Adapters\Phpunit\Listener->startTest(Object(PHPUnit\Framework\WarningTestCase))
#1 /vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(PHPUnit\Framework\WarningTestCase))
#2 /vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(PHPUnit\Framework\WarningTestCase))
#3 /vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#4 /vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Fr in /vendor/nunomaduro/collision/src/Adapters/Phpunit/Listener.php on line 141
```

Expected output
```
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

W                                                                   1 / 1 (100%)

Time: 105 ms, Memory: 6.00MB

There was 1 warning:

1) Warning
No tests found in class "Tests\MyTest".

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
```

**Comment by nunomaduro** [comment]
@sw-double You problem should be fixed on the version `v1.1.18`. Do you mind of performing `composer update nunomaduro/collision` and check it?
