### ISSUE TITLE
Does not work with Laravel 5.8

### ISSUE THREAD

**Issue by mfn** [nunomaduro/collision#61]
- Had it installed on Laravel 5.7
- Upgraded to 5.8
- outcome:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 8 installs, 8 updates, 4 removals
  - Removing lcobucci/jwt (3.2.5)
  - Removing laravel/slack-notification-channel (v1.0.3)
  - Removing laravel/nexmo-notification-channel (v1.0.1)
  - Removing nexmo/client (1.6.2)
  - Installing phpoption/phpoption (1.5.0): Loading from cache
  - Updating vlucas/phpdotenv (v2.6.1 => v3.3.2): Loading from cache
  - Updating laravel/framework (v5.7.28 => v5.8.2): Loading from cache
  - Updating folklore/graphql (v1.1.0.1 => v1.1.0.1): Loading from cache
  - Installing psr/http-factory (1.0.0): Loading from cache
  - Updating zendframework/zend-diactoros (1.8.6 => 2.1.1): Loading from cache
  - Installing symfony/options-resolver (v4.2.3): Loading from cache
  - Installing clue/stream-filter (v1.4.0): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing php-http/message (1.7.2): Loading from cache
  - Installing php-http/discovery (1.6.1): Loading from cache
  - Installing php-http/client-common (1.9.1): Loading from cache
  - Updating sentry/sentry (1.10.0 => 2.0.0): Loading from cache
  - Downgrading sentry/sentry-laravel (0.11.0 => 0.8.0): Loading from cache
  - Updating spatie/laravel-csp (2.1.3 => 2.2.0): Loading from cache
php-http/message suggests installing slim/slim (Used with Slim Framework PSR-7 implementation)
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is recommended for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
php-http/client-common suggests installing php-http/logger-plugin (PSR-3 Logger plugin)
php-http/client-common suggests installing php-http/cache-plugin (PSR-6 Cache plugin)
php-http/client-common suggests installing php-http/stopwatch-plugin (Symfony Stopwatch plugin)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Class NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Debug\ExceptionHandler::shouldReport) in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php on line 27
PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php:44
Stack trace:
#0 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): NunoMaduro\Collision\Adapters\Laravel\CollisionServiceProvider->NunoMaduro\Collision\Adapters\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->build(Object(Closure))
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foun in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php on line 44
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

Basically, artisan doens't work:
```sh
$ ./artisan --version
PHP Fatal error:  Class NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Debug\ExceptionHandler::shouldReport) in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php on line 27
PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php:44
Stack trace:
#0 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): NunoMaduro\Collision\Adapters\Laravel\CollisionServiceProvider->NunoMaduro\Collision\Adapters\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->build(Object(Closure))
#2 /vagrant/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /vagrant/project/vendor/laravel/framework/src/Illuminate/Foun in /vagrant/project/vendor/nunomaduro/collision/src/Adapters/Laravel/CollisionServiceProvider.php on line 44
```

**Comment by nunomaduro** [comment]
Seems that you are using an old version of collision.

**Comment by mfn** [comment]
💥 true, sorry for the noise; I was still on `^1.1` 🤷‍♀️
